import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

import 'package:brisconnect/models/audience_interaction.dart';
import 'package:brisconnect/models/promotion_schedule.dart';

/// A recommended day/time window for posting a promotion.
class PostRecommendation {
  final int dayOfWeek; // 1 = Monday, 7 = Sunday
  final int startHour; // 0-23
  final int endHour; // 1-24
  final double engagementScore;
  final int interactionCount;
  final String explanation;

  const PostRecommendation({
    required this.dayOfWeek,
    required this.startHour,
    required this.endHour,
    required this.engagementScore,
    required this.interactionCount,
    required this.explanation,
  });

  String get dayLabel {
    const days = [
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday',
    ];
    return days[dayOfWeek - 1];
  }

  String get timeRangeLabel {
    final startPeriod = startHour < 12 ? 'am' : 'pm';
    final displayStart = startHour == 0
        ? 12
        : startHour > 12
            ? startHour - 12
            : startHour;
    final endPeriod = endHour < 12 || endHour == 24 ? 'am' : 'pm';
    final displayEnd = endHour == 0
        ? 12
        : endHour > 12
            ? endHour - 12
            : endHour;
    return '$displayStart$startPeriod–$displayEnd$endPeriod';
  }
}

/// Result of the best-time-to-post analysis.
class BestTimeToPostResult {
  final bool hasEnoughData;
  final List<PostRecommendation> recommendations;
  final String? insufficientDataReason;

  const BestTimeToPostResult({
    required this.hasEnoughData,
    required this.recommendations,
    this.insufficientDataReason,
  });

  static const BestTimeToPostResult insufficient = BestTimeToPostResult(
    hasEnoughData: false,
    recommendations: [],
    insufficientDataReason:
        'We need at least 14 days of engagement history to recommend the best times.',
  );
}

/// Service that recommends optimal promotion posting times based on anonymised
/// audience engagement history.
///
/// Recommendations are generated by bucketing interactions into day-of-week /
/// hour-of-day cells and ranking cells by engagement density. A minimum of
/// 14 days of data and statistically meaningful variance are required.
class BestTimeToPostService {
  final FirebaseFirestore _firestore;

  BestTimeToPostService({FirebaseFirestore? firestore})
      : _firestore = firestore ?? FirebaseFirestore.instance;

  static const String _interactionsCollection = 'audience_interactions';
  static const String _promotionsCollection = 'promotions';
  static const int _minDaysOfHistory = 14;
  static const int _windowHours = 2;

  /// Returns recommended posting windows for the businesses owned by [ownerId].
  ///
  /// The analysis considers the last [lookbackDays] days of audience
  /// interactions. Results are capped to the top [maxRecommendations].
  Future<BestTimeToPostResult> getRecommendations(
    String ownerId, {
    int lookbackDays = 90,
    int maxRecommendations = 3,
  }) async {
    if (ownerId.trim().isEmpty) return BestTimeToPostResult.insufficient;

    final now = DateTime.now();
    final cutoff = now.subtract(Duration(days: lookbackDays));

    final interactions = await _fetchInteractions(ownerId, cutoff, now);
    if (interactions.isEmpty) return BestTimeToPostResult.insufficient;

    final historySpan = _historySpanDays(interactions);
    if (historySpan < _minDaysOfHistory) {
      return const BestTimeToPostResult(
        hasEnoughData: false,
        recommendations: [],
        insufficientDataReason:
            'Keep engaging customers. We need 14 days of history to find reliable patterns.',
      );
    }

    final bucketCounts = _bucketInteractions(interactions);
    if (!_hasSignificantVariance(bucketCounts)) {
      return const BestTimeToPostResult(
        hasEnoughData: false,
        recommendations: [],
        insufficientDataReason:
            'Engagement is spread fairly evenly, so no strong pattern has emerged yet.',
      );
    }

    final ranked = _rankBuckets(bucketCounts);
    final recommendations = _buildRecommendations(
      ranked,
      interactions.length,
      maxRecommendations,
    );

    return BestTimeToPostResult(
      hasEnoughData: true,
      recommendations: recommendations,
    );
  }

  Future<List<AudienceInteraction>> _fetchInteractions(
    String ownerId,
    DateTime start,
    DateTime end,
  ) async {
    final snapshot = await _firestore
        .collection(_interactionsCollection)
        .where('ownerId', isEqualTo: ownerId)
        .where('timestamp', isGreaterThanOrEqualTo: Timestamp.fromDate(start))
        .where('timestamp', isLessThanOrEqualTo: Timestamp.fromDate(end))
        .get();
    return snapshot.docs
        .map((doc) => AudienceInteraction.fromFirestore(doc))
        .toList();
  }

  int _historySpanDays(List<AudienceInteraction> interactions) {
    final timestamps = interactions.map((i) => i.timestamp).toList()..sort();
    if (timestamps.length < 2) return 0;
    return timestamps.last.difference(timestamps.first).inDays;
  }

  /// Returns a map of dayOfWeek -> hour -> count.
  Map<int, Map<int, int>> _bucketInteractions(
    List<AudienceInteraction> interactions,
  ) {
    final buckets = <int, Map<int, int>>{};
    for (final interaction in interactions) {
      final local = interaction.timestamp.toLocal();
      final day = local.weekday;
      final hour = local.hour;
      buckets.putIfAbsent(day, () => <int, int>{})[hour] =
          (buckets[day]![hour] ?? 0) + 1;
    }
    return buckets;
  }

  /// Returns true if at least one bucket has meaningfully more interactions
  /// than the mean, indicating a pattern rather than random noise.
  bool _hasSignificantVariance(Map<int, Map<int, int>> buckets) {
    final values = buckets.values.expand((m) => m.values).toList();
    if (values.isEmpty) return false;
    final mean = values.reduce((a, b) => a + b) / values.length;
    final variance = values
            .map((v) => pow(v - mean, 2))
            .reduce((a, b) => a + b) /
        values.length;
    final stdDev = sqrt(variance);
    return stdDev > mean * 0.3;
  }

  List<MapEntry<_BucketKey, int>> _rankBuckets(
    Map<int, Map<int, int>> buckets,
  ) {
    final entries = <MapEntry<_BucketKey, int>>[];
    buckets.forEach((day, hours) {
      hours.forEach((hour, interactionCount) {
        entries.add(MapEntry(_BucketKey(day: day, hour: hour), interactionCount));
      });
    });
    entries.sort((a, b) => b.value.compareTo(a.value));
    return entries;
  }

  List<PostRecommendation> _buildRecommendations(
    List<MapEntry<_BucketKey, int>> ranked,
    int totalInteractions,
    int maxRecommendations,
  ) {
    if (ranked.isEmpty) return const [];

    final maxCount = ranked.first.value;
    final selected = <PostRecommendation>[];
    final usedDayHourPairs = <_BucketKey>{};

    for (final entry in ranked) {
      if (selected.length >= maxRecommendations) break;
      final day = entry.key.day;
      final hour = entry.key.hour;
      final pair = _BucketKey(day: day, hour: hour);

      // Avoid duplicate day/hour slots while allowing multiple times per day.
      if (usedDayHourPairs.contains(pair)) continue;
      usedDayHourPairs.add(pair);

      final startHour = hour;
      final endHour = (hour + _windowHours).clamp(1, 24);
      final count = entry.value;
      final score = count / maxCount;

      selected.add(
        _makeRecommendation(
          day: day,
          startHour: startHour,
          endHour: endHour,
          score: score,
          count: count,
        ),
      );
    }

    return selected;
  }

  PostRecommendation _makeRecommendation({
    required int day,
    required int startHour,
    required int endHour,
    required double score,
    required int count,
  }) {
    return PostRecommendation(
      dayOfWeek: day,
      startHour: startHour,
      endHour: endHour,
      engagementScore: score,
      interactionCount: count,
      explanation:
          'Highest engagement on ${PostRecommendation(dayOfWeek: day, startHour: startHour, endHour: endHour, engagementScore: score, interactionCount: count, explanation: '').dayLabel}s ${PostRecommendation(dayOfWeek: day, startHour: startHour, endHour: endHour, engagementScore: score, interactionCount: count, explanation: '').timeRangeLabel}',
    );
  }

  /// Checks whether [scheduledAt] falls outside all recommended windows.
  /// Returns a soft warning message if so, or null if it aligns.
  String? warningForSchedule(
    DateTime scheduledAt,
    List<PostRecommendation> recommendations,
  ) {
    if (recommendations.isEmpty) return null;

    final local = scheduledAt.toLocal();
    final day = local.weekday;
    final hour = local.hour;

    final matches = recommendations.any((r) {
      return r.dayOfWeek == day && hour >= r.startHour && hour < r.endHour;
    });

    if (matches) return null;

    final suggested = recommendations.first;
    return 'This time is outside your recommended window '
        '(${suggested.dayLabel}s ${suggested.timeRangeLabel}). '
        'It may get less visibility.';
  }

  /// Records a scheduled promotion for future historical analysis.
  Future<void> recordScheduledPromotion(PromotionSchedule promotion) async {
    try {
      await _firestore
          .collection(_promotionsCollection)
          .add(promotion.toFirestore());
    } catch (e) {
      debugPrint('[BestTimeToPostService] recordScheduledPromotion failed: $e');
    }
  }
}

class _BucketKey {
  final int day;
  final int hour;

  const _BucketKey({required this.day, required this.hour});

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is _BucketKey && other.day == day && other.hour == hour;

  @override
  int get hashCode => Object.hash(day, hour);
}
