// File generated by the FlutterFire CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBosCAp3VFaZZ01YIEyhSZLSMn8L3--NIs',
    appId: '1:2073694703:web:72dea72558f80bcbfa261a',
    messagingSenderId: '2073694703',
    projectId: 'brisconnect-68b78',
    authDomain: 'brisconnect-68b78.firebaseapp.com',
    storageBucket: 'brisconnect-68b78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEVyIedbCHom8SImaasL4e7ahFeldBBBY',
    appId: '1:2073694703:android:78082838113cac65fa261a',
    messagingSenderId: '2073694703',
    projectId: 'brisconnect-68b78',
    storageBucket: 'brisconnect-68b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh0PHiARbQM8WCeGHtppQEcIKOfyPGMhU',
    appId: '1:2073694703:ios:28fa782e5fe1479cfa261a',
    messagingSenderId: '2073694703',
    projectId: 'brisconnect-68b78',
    storageBucket: 'brisconnect-68b78.firebasestorage.app',
    iosBundleId: 'com.june.brisconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh0PHiARbQM8WCeGHtppQEcIKOfyPGMhU',
    appId: '1:2073694703:ios:28fa782e5fe1479cfa261a',
    messagingSenderId: '2073694703',
    projectId: 'brisconnect-68b78',
    storageBucket: 'brisconnect-68b78.firebasestorage.app',
    iosBundleId: 'com.june.brisconnect',
  );
}