// File generated by the FlutterFire CLI.
// https://github.com/firebase/flutterfire_cli

import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNu_example_web_key',
    appId: '1:123456789:web:abcdefg1234567',
    messagingSenderId: '123456789',
    projectId: 'brisconnect-dev',
    authDomain: 'brisconnect-dev.firebaseapp.com',
    storageBucket: 'brisconnect-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEVyIedbCHom8SImaasL4e7ahFeldBBBY',
    appId: '1:2073694703:android:78082838113cac65fa261a',
    messagingSenderId: '2073694703',
    projectId: 'brisconnect-68b78',
    storageBucket: 'brisconnect-68b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNu_example_ios_key',
    appId: '1:123456789:ios:abcdefg1234567',
    messagingSenderId: '123456789',
    projectId: 'brisconnect-dev',
    storageBucket: 'brisconnect-dev.appspot.com',
    iosBundleId: 'com.example.brisconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNu_example_macos_key',
    appId: '1:123456789:macos:abcdefg1234567',
    messagingSenderId: '123456789',
    projectId: 'brisconnect-dev',
    storageBucket: 'brisconnect-dev.appspot.com',
    iosBundleId: 'com.example.brisconnect',
  );
}
