-- Query samples for Local user login flow
-- Depends on schema in docs/UserStory_Local_Login_MySQL_Schema.sql

-- Parameters used in examples:
-- :identifier        => email or username entered by user
-- :password_hash     => hash generated by app/server for comparison flow
-- :ip_address        => request source IP
-- :user_agent        => request user-agent
-- :session_hash      => SHA-256 hash of access token
-- :refresh_hash      => SHA-256 hash of refresh token
-- :restore_hash      => SHA-256 hash of restore token/key
-- :expires_at        => session expiry timestamp
-- :device_id         => optional device identifier
-- :route_path        => route user is trying to access (e.g. /local/dashboard)
-- :http_method       => GET/POST/PUT/PATCH/DELETE

-- 1) Find candidate account (email or username)
SELECT
  id,
  email,
  username,
  password_hash,
  account_type,
  status,
  failed_login_count,
  locked_until
FROM auth_users
WHERE email = :identifier OR username = :identifier
LIMIT 1;

-- 2) Record failed attempt (invalid credentials)
INSERT INTO login_attempts (
  email_attempted,
  account_type_attempted,
  user_id,
  was_successful,
  failure_reason,
  ip_address,
  user_agent,
  attempted_at
) VALUES (
  :identifier,
  'local',
  :user_id,
  0,
  'invalid_credentials',
  :ip_address,
  :user_agent,
  CURRENT_TIMESTAMP(3)
);

-- 3) Increment failed count and lock after threshold (example threshold = 5)
UPDATE auth_users
SET
  failed_login_count = failed_login_count + 1,
  locked_until = CASE
    WHEN failed_login_count + 1 >= 5 THEN DATE_ADD(CURRENT_TIMESTAMP(3), INTERVAL 15 MINUTE)
    ELSE locked_until
  END,
  updated_at = CURRENT_TIMESTAMP(3)
WHERE id = :user_id;

-- 4) Check local role authorization
SELECT 1 AS has_local_role
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = :user_id
  AND r.role_code = 'local_user'
LIMIT 1;

-- 5) Record wrong-role attempt
INSERT INTO login_attempts (
  email_attempted,
  account_type_attempted,
  user_id,
  was_successful,
  failure_reason,
  ip_address,
  user_agent,
  attempted_at
) VALUES (
  :identifier,
  'local',
  :user_id,
  0,
  'wrong_role',
  :ip_address,
  :user_agent,
  CURRENT_TIMESTAMP(3)
);

-- 6) Create successful session
INSERT INTO auth_sessions (
  user_id,
  session_token_hash,
  refresh_token_hash,
  restore_key_hash,
  ip_address,
  user_agent,
  device_id,
  is_persistent,
  is_revoked,
  issued_at,
  expires_at,
  last_seen_at
) VALUES (
  :user_id,
  :session_hash,
  :refresh_hash,
  :restore_hash,
  :ip_address,
  :user_agent,
  :device_id,
  1,
  0,
  CURRENT_TIMESTAMP(3),
  :expires_at,
  CURRENT_TIMESTAMP(3)
);

-- 7) Mark successful login and reset counters
UPDATE auth_users
SET
  last_login_at = CURRENT_TIMESTAMP(3),
  failed_login_count = 0,
  locked_until = NULL,
  updated_at = CURRENT_TIMESTAMP(3)
WHERE id = :user_id;

INSERT INTO login_attempts (
  email_attempted,
  account_type_attempted,
  user_id,
  was_successful,
  failure_reason,
  ip_address,
  user_agent,
  attempted_at
) VALUES (
  :identifier,
  'local',
  :user_id,
  1,
  NULL,
  :ip_address,
  :user_agent,
  CURRENT_TIMESTAMP(3)
);

-- 8) Restore session on app relaunch
SELECT
  s.id,
  s.user_id,
  s.expires_at,
  s.is_revoked,
  u.status,
  u.account_type
FROM auth_sessions s
JOIN auth_users u ON u.id = s.user_id
WHERE s.restore_key_hash = :restore_hash
  AND s.is_revoked = 0
  AND s.expires_at > CURRENT_TIMESTAMP(3)
  AND u.status = 'active'
  AND u.account_type = 'local'
LIMIT 1;

-- 9) Route authorization check for local-only path
SELECT 1 AS route_allowed
FROM route_policies rp
JOIN permissions p ON p.id = rp.permission_id
JOIN role_permissions rperm ON rperm.permission_id = p.id
JOIN user_roles ur ON ur.role_id = rperm.role_id
WHERE ur.user_id = :user_id
  AND rp.is_enabled = 1
  AND (:http_method = rp.http_method OR rp.http_method = '*')
  AND :route_path LIKE REPLACE(rp.route_pattern, '%', '%')
LIMIT 1;

-- 10) Revoke session on logout
UPDATE auth_sessions
SET
  is_revoked = 1,
  revoked_at = CURRENT_TIMESTAMP(3),
  revoked_reason = 'user_logout'
WHERE session_token_hash = :session_hash
  AND is_revoked = 0;
